version: '3'

services:
        db:
                image: mariadb
                restart: always
                volumes:
                        - db:/var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_PASSWORD=nextcloud
                        - MYSQL_DATABASE=nextcloud
                        - MYSQL_USER=nextcloud
        nextcloud:
                image: nextcloud:latest
                ports:
                        - 8080:80
                links:
                        - db
                restart: always
                volumes:
                        - nextcloud:/var/www/html
volumes:
        nextcloud:
        db:
